### ISSUE TITLE
Need website logo

### ISSUE THREAD

**Issue by mdombrovsky** [mdombrovsky/React-Website#4]

**Comment by mocouff** [comment]
I am a student, I saw that you wanted a logo? Is it possible to have explanations?
Thank's

**Comment by mdombrovsky** [comment]
I was looking for a logo for the website in the browser tab. Something that is a cool design of the letters M and D, if you are artistically skilled I would very much appreciate if you could help me out.

**Comment by mocouff** [comment]
Yes of course do you have other constraints? color ? shapes? etc.

**Comment by mocouff** [comment]
Could i have the link of your website???

**Comment by mdombrovsky** [comment]
Sorry I took so long to reply, the website name should be inside the CNAME in this repo currently its at https://mdombrov.digital/#/

I have no constraints really, just use your best judgement?

**Comment by mocouff** [comment]
Ok, i start your logo !

**Comment by mocouff** [comment]
![Logo 1](https://user-images.githubusercontent.com/59663880/72904586-6d9d3d00-3d2f-11ea-833e-ec8f2d332336.png)
![Logo 2](https://user-images.githubusercontent.com/59663880/72904587-6d9d3d00-3d2f-11ea-983f-de2c3c0cb94e.png)

**Comment by mdombrovsky** [comment]
Wow thanks, thats wonderful, I think I will be using the top one for my website, Il update my website soon.

**Comment by mdombrovsky** [comment]
@mocouff, you should do a pull request on this repo so that your contribution will be shown.

**Comment by mocouff** [comment]
Can you explain to me please ? I don't understand

**Comment by mdombrovsky** [comment]
If you want you can upload the images right to the repo through a pull request so that you will be able to get full credit for the images.
